accounts/urls.py
from django.urls import path
from .views import register, login, logout

app_name = 'account'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

microapp/urls.py
from django.urls import path
from .views import index, products, product_details, cart, checkout, account, wishlist, contact

urlpatterns = [
    path('index/', index, name='index'),
    path('products/', products, name='products'),
    path('product_details/', product_details, name='details_product' ),
    path('cart/', cart, name='carts' ),
    path('checkout/', checkout, name='checkouts'),
    path('my_account/', account, name='my_account'),
    path('wishlist/', wishlist, name='wish'),
    # path('login_register/', login_register, name='register'),
    path('contact/', contact,  name='contact'),
]

microstock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('microapp.urls')),
    path('account/', include('accounts.urls', namespace='account')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from email.policy import default
from enum import unique
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, AbstractUser

# Create your models here.
class UserAccountManager(BaseUserManager): #function to create user
    def create_user(self, first_name, last_name, username, email,  password = None):
        if not username:
            raise ValueError("User must have a username")
        
        if not email:
            raise ValueError("User must have an email")
        
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    #create super user
    def create_superuser(self, first_name, last_name, username, email, password): # function to create and save super user
        user = self.create_user(
            email=email,
            first_name = first_name,
            last_name = last_name,
            username = username,
            password = password  
            
        )
        user.is_admin = True
        user.is_active = True
        user.is_superadmin = True
        user.is_staff = True
        user.save(using = self._db)

        return user

# user creation fields
class User(AbstractBaseUser):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    username = models.CharField(max_length = 50, unique=True)
    email = models.EmailField(max_length = 50, unique = True)
    phone_number = PhoneNumberField(max_length= 30, unique=True, null=True)

    date_joined = models.DateTimeField(auto_now_add = True)
    last_login = models.DateTimeField(auto_now = True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default = True)
    is_superadmin = models.BooleanField(default = False)


    objects = UserAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    def __str__(self):
        return self.email
    
    #to set permission for user
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, add_label):
        return True

category/models.py
from django.db import models

# Create your models here.

microapp/models.py
from django.db import models
from django.utils import timezone

class Category(models.Model):
    title = models.CharField(max_length = 150)
    description = models.CharField(max_length = 150)
    slug = models.SlugField()
    order = models.BooleanField(default = 0)
    timestamp = models.DateTimeField(auto_now_add = True, auto_now = False)
    updated = models.DateTimeField(auto_now_add = True, auto_now = False)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

class CategoryImage(models.Model):
    title = models.CharField(max_length = 150, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete = models.CASCADE, related_name = "category")
    image = models.ImageField(upload_to='category/image')
    slug = models.SlugField()
    featured_image = models.BooleanField(default = False)
    updated = models.DateTimeField(auto_now_add = False, auto_now = True)

    class Meta:
        verbose_name = 'Category Image'

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from .models import User

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Enter Password', 'class':'form-control'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password', 'class':'form-control'}))
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'password']

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'

        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter Last Name'

        self.fields['email'].widget.attrs['placeholder'] = 'Enter E-mail Address'

        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter Phone Number'

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    #using clean method to confirm password
    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password != confirm_password: 
            raise forms.ValidationError("Password does not match! ")

accounts/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from .models import User

# Create your views here.

def  register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            phone_number = form.cleaned_data['phone_number']

            username = email.split('@')[0] #obtain username from email

            user = User.objects.create_user(first_name = first_name, last_name = last_name, email = email, password = password, username = username)

            user.phone_number = phone_number
            user.save()
    else:
        form = RegistrationForm()
            
    context ={
        'form' : form
    }
    return render(request, 'accounts/register.html', context)

def login(request):
    return render(request, 'accounts/login.html')

def logout(request):
    return redirect('/')

category/views.py
from django.shortcuts import render

# Create your views here.

microapp/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    return render(request, 'menu_pages/home.html')

def products(request):
    return render(request, 'menu_pages/products.html')

def product_details(request):
    return render(request, 'menu_pages/product_details.html')

def cart(request):
    return render(request, 'menu_pages/cart.html')

def checkout(request):
    return render(request, 'menu_pages/checkout.html')

def account(request):
    return render(request, 'menu_pages/my-account.html')

def wishlist(request):
    return render(request, 'menu_pages/wishlist.html')

# def  login_register(request):
#     return render(request, 'menu_pages/register.html')

def  contact(request):
    return render(request, 'menu_pages/contact.html')

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">

            <li class="breadcrumb-item active">Login</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- Login Start -->
<div class="login">
    <div class="container-fluid">
      <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
        <form class="" action="index.html" method="post" style="width:100%; padding:20px">

                <div class="form-group">
                    <label>E-mail / Username</label>
                    <input class="form-control" type="text" placeholder="E-mail / Username">
                </div>
                <div class="form-group">
                    <label>Password</label>
                    <input class="form-control" type="text" placeholder="Password">
                </div>
                <div class="col-md-12">
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="newaccount">
                        <label class="custom-control-label" for="newaccount">Keep me signed in</label>
                    </div>
                </div>
                <div class="col-md-12">
                    <button class="btn">Submit</button>
                </div>
        </form>



                </div>
            </div>

    </div>
    <p class="text-center mt-4">Have an account?
       <a href="{% url 'account:login' %}">Log In</a>
    </p>
    <br><br>
</div>
</div>

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Products</a></li>
            <li class="breadcrumb-item active">Register</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->
<!-- Login Start -->
<div class="login">
    <div class="container-fluid">
        <div class="card mx-auto" style="max-width:720px; margin-top:40px;">
            <form class="" action="{% url 'account:register' %}" method="post">
                {% csrf_token %}
                <div class="register-form">
                    <div class="row">
                        <div class="col-md-6">
                            <label>First Name</label>
                            {{ form.first_name }}
                        </div>
                        <div class="col-md-6">
                            <label>Last Name"</label>
                            {{ form.last_name }}
                        </div>
                        <div class="col-md-6">
                            <label>E-mail</label>
                            {{ form.email }}
                        </div>
                        <div class="col-md-6">
                            <label>Mobile No</label>
                            {{ form.phone_number }}
                        </div>
                        <div class="col-md-6">
                            <label>Password</label>
                            {{ form.password }}
                        </div>
                        <div class="col-md-6">
                            <label>Confirm Password</label>
                            {{ form.confirm_password }}
                        </div>
                        <div class="col-md-12">
                            <button class="btn btn-primary btn-block">Submit</button>
                        </div>
                        {{ form.email.errors }}
                        {{ form.non_field_errors }}
            </form>



        </div>
    </div>

</div>
<p class="text-center mt-4">Have an account?
    <a href="#">Log In</a>
</p>
<br><br>
</div>
</div>
<!-- Login End -->
{% endblock %}

templates/accounts/register2.html
hello

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Microstock Agency</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="eCommerce HTML Template Free Download" name="keywords">
    <meta content="eCommerce HTML Template Free Download" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap"
        rel="stylesheet">

    <!-- CSS Libraries -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'lib/slick/slick.css' %}">
    <link rel="stylesheet" href="{% static 'lib/slick/slick-theme.css' %}">

    <!-- Template Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <!-- Nav Bar Start -->
    <div class="nav">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                <a href="#" class="navbar-brand">MENU</a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto">
                        <a href="{% url 'index' %}" class="nav-item nav-link active">Home</a>
                        <a href="{% url 'products' %}" class="nav-item nav-link">Products</a>
                        <a href="{% url 'details_product' %}" class="nav-item nav-link">Product Detail</a>
                        <a href="{% url 'carts' %}" class="nav-item nav-link">Cart</a>
                        <a href="{% url 'checkouts' %}" class="nav-item nav-link">Checkout</a>
                        <a href="{% url 'my_account' %}" class="nav-item nav-link">My Account</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">More Pages</a>
                            <div class="dropdown-menu">
                                <a href="{% url 'wish' %}" class="dropdown-item">Wishlist</a>
                                <a href="{% url 'account:register' %}" class="dropdown-item">Login & Register</a>
                                <a href="{% url 'contact' %}" class="dropdown-item">Contact Us</a>
                            </div>
                        </div>
                    </div>
                    <div class="navbar-nav ml-auto">
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">User Account</a>
                            <div class="dropdown-menu">
                                <a href="{% url 'account:login' %}" class="dropdown-item">Login</a>
                                <a href="{% url 'account:register'  %}" class="dropdown-item">Register</a>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- Nav Bar End -->

    <!-- Bottom Bar Start -->
    <div class="bottom-bar">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-md-3">
                    <div class="logo">
                        <a href="index.html">
                            <img src="/static/img/logo.png" alt="Logo">
                        </a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="search">
                        <input type="text" placeholder="Search">
                        <button><i class="fa fa-search"></i></button>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="user">
                        <a href="wishlist.html" class="btn wishlist">
                            <i class="fa fa-heart"></i>
                            <span>(0)</span>
                        </a>
                        <a href="cart.html" class="btn cart">
                            <i class="fa fa-shopping-cart"></i>
                            <span>(0)</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Bottom Bar End -->

    {% block content %}{% endblock %}
    <!-- Footer Start -->
    <div class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <h2>Get in Touch</h2>
                        <div class="contact-info">
                            <p><i class="fa fa-map-marker"></i>123 E Store, Los Angeles, USA</p>
                            <p><i class="fa fa-envelope"></i>email@example.com</p>
                            <p><i class="fa fa-phone"></i>+123-456-7890</p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <h2>Follow Us</h2>
                        <div class="contact-info">
                            <div class="social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                                <a href=""><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <h2>Company Info</h2>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Terms & Condition</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <h2>Purchase Info</h2>
                        <ul>
                            <li><a href="#">Pyament Policy</a></li>
                            <li><a href="#">Shipping Policy</a></li>
                            <li><a href="#">Return Policy</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row payment align-items-center">
                <div class="col-md-6">
                    <div class="payment-method">
                        <h2>We Accept:</h2>
                        <img src="/static/img/payment-method.png" alt="Payment Method" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="payment-security">
                        <h2>Secured By:</h2>
                        <img src="/static/img/godaddy.svg" alt="Payment Security" />
                        <img src="/static/img/norton.svg" alt="Payment Security" />
                        <img src="/static/img/ssl.svg" alt="Payment Security" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->

    <!-- Footer Bottom Start -->
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-6 copyright">
                    <p>Copyright &copy; <a href="#">Nelly_B</a>. All Rights Reserved</p>
                </div>

                <div class="col-md-6 template-by">
                    <p>Template By <a href="#">Nelly_B</a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer Bottom End -->

    <!-- Back to Top -->
    <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/slick/slick.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/menu_pages/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Products</a></li>
            <li class="breadcrumb-item active">Cart</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- Cart Start -->
<div class="cart-page">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8">
                <div class="cart-page-inner">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Product</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th>Remove</th>
                                </tr>
                            </thead>
                            <tbody class="align-middle">
                                <tr>
                                    <td>
                                        <div class="img">
                                            <a href="#"><img src="/static/img/product-1.jpg" alt="Image"></a>
                                            <p>Product Name</p>
                                        </div>
                                    </td>
                                    <td>$99</td>
                                    <td>
                                        <div class="qty">
                                            <button class="btn-minus"><i class="fa fa-minus"></i></button>
                                            <input type="text" value="1">
                                            <button class="btn-plus"><i class="fa fa-plus"></i></button>
                                        </div>
                                    </td>
                                    <td>$99</td>
                                    <td><button><i class="fa fa-trash"></i></button></td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="img">
                                            <a href="#"><img src="/static/img/product-2.jpg" alt="Image"></a>
                                            <p>Product Name</p>
                                        </div>
                                    </td>
                                    <td>$99</td>
                                    <td>
                                        <div class="qty">
                                            <button class="btn-minus"><i class="fa fa-minus"></i></button>
                                            <input type="text" value="1">
                                            <button class="btn-plus"><i class="fa fa-plus"></i></button>
                                        </div>
                                    </td>
                                    <td>$99</td>
                                    <td><button><i class="fa fa-trash"></i></button></td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="img">
                                            <a href="#"><img src="/static/img/product-3.jpg" alt="Image"></a>
                                            <p>Product Name</p>
                                        </div>
                                    </td>
                                    <td>$99</td>
                                    <td>
                                        <div class="qty">
                                            <button class="btn-minus"><i class="fa fa-minus"></i></button>
                                            <input type="text" value="1">
                                            <button class="btn-plus"><i class="fa fa-plus"></i></button>
                                        </div>
                                    </td>
                                    <td>$99</td>
                                    <td><button><i class="fa fa-trash"></i></button></td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="img">
                                            <a href="#"><img src="/static/img/product-4.jpg" alt="Image"></a>
                                            <p>Product Name</p>
                                        </div>
                                    </td>
                                    <td>$99</td>
                                    <td>
                                        <div class="qty">
                                            <button class="btn-minus"><i class="fa fa-minus"></i></button>
                                            <input type="text" value="1">
                                            <button class="btn-plus"><i class="fa fa-plus"></i></button>
                                        </div>
                                    </td>
                                    <td>$99</td>
                                    <td><button><i class="fa fa-trash"></i></button></td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="img">
                                            <a href="#"><img src="/static/img/product-5.jpg" alt="Image"></a>
                                            <p>Product Name</p>
                                        </div>
                                    </td>
                                    <td>$99</td>
                                    <td>
                                        <div class="qty">
                                            <button class="btn-minus"><i class="fa fa-minus"></i></button>
                                            <input type="text" value="1">
                                            <button class="btn-plus"><i class="fa fa-plus"></i></button>
                                        </div>
                                    </td>
                                    <td>$99</td>
                                    <td><button><i class="fa fa-trash"></i></button></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="cart-page-inner">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="coupon">
                                <input type="text" placeholder="Coupon Code">
                                <button>Apply Code</button>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="cart-summary">
                                <div class="cart-content">
                                    <h1>Cart Summary</h1>
                                    <p>Sub Total<span>$99</span></p>
                                    <p>Shipping Cost<span>$1</span></p>
                                    <h2>Grand Total<span>$100</span></h2>
                                </div>
                                <div class="cart-btn">
                                    <button>Update Cart</button>
                                    <button>Checkout</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart End -->

{% endblock %}